services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    container_name: telegram_proxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    environment:
      ALLOWED_DOMAINS: "proxy.gladiapet.com"
      SITES: "proxy.gladiapet.com=localhost:8080"
      FORCE_HTTPS: "true"
    volumes:
      - ssl_data:/etc/resty-auto-ssl
      - ./nginx.conf:/etc/nginx/conf.d/rewrite.conf:ro

volumes:
  ssl_data:
